services:
  redis-cluster:
    image: redis:latest
    environment:
      - REDIS_TLS_ENABLED=no
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "PING"]
      interval: 5s
      timeout: 3s
      retries: 10

  cachegrid:
    image: cachegrid-dockerized
    volumes:
      - ./keys-dev.json:/opt/keys.json:ro
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATA_REDIS_HOST=redis-cluster
      - SPRING_DATA_REDIS_PORT=6379
      - KEYS_FILE_PATH=/opt/keys.json
    ports:
      - "8080:8080"
    depends_on:
      - redis-cluster