server.port=8080

logging.level.root=INFO
logging.level.com.ott.cachegrid=DEBUG
logging.level.org.springframework.data.redis=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

spring.data.redis.host=localhost
spring.data.redis.port=8000

spring.data.redis.timeout=2000ms