server.port=8080

logging.level.root=INFO
logging.level.com.ott.cachegrid=DEBUG
logging.level.org.springframework.data.redis=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

spring.redis.host=localhost
spring.redis.cluster.ports=8000

spring..redis.timeout=2000ms

spring.data.redis.lettuce.pool.max-active=6
spring.data.redis.lettuce.pool.max-idle=6
spring.data.redis.lettuce.pool.min-idle=0